services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_apache_server
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    networks:
      - app_network

  db:
    image: mysql:5.7
    container_name: mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: omshubh123
      MYSQL_DATABASE: zenpetsdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql  # Persistent volume for MySQL data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:  # Declare the volume for MySQL
